name: Docker build & push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set date tag
        id: date
        run: echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_L }}
          password: ${{ secrets.DH_T }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            bovs/my_lmp:latest
            bovs/my_lmp:${{ env.DATE_TAG }}
